### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by gedw99** [jelic98/rafpored#1]
really great example of flutter .

**Comment by jelic98** [comment]
Thank you!

**Comment by gedw99** [comment]
Is the server code public or at least the API maybe. Its because i want to see if i can code generate the dart code from a Restful JSON interface.

**Comment by gedw99** [comment]
No problem.

I can codegen the server side API purely from the client side JSON
structure model.
Will codegen the server in golang using Goa Design.

Anyways thanks for the front end. I just want to adapt it to a different
problem domain that has similar needs. It's for doctors collaborating in
developing countries.

Cheers

Ged

**Comment by jelic98** [comment]
Thats great. I will close this issue now. If you have any questions or possible improvements please ask.
